steps:
- name: gcr.io/cloud-builders/gcloud
  args:
  - functions
  - deploy
  - slackRequestLog
  - --trigger-topic=request-logs
  - --runtime=nodejs8
  - --update-env-vars=SLACK_WEBHOOK_URL=${_SLACK_WEBHOOK_URL}
